[package]
name = "typesetting-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
anyhow = "1.0"
thiserror = "1.0"
regex = "1.0"

[[bin]]
name = "typesetting-engine"
path = "src/main.rs"

[lib]
crate-type = ["rlib"]